### ISSUE TITLE
document Graph.__getitem__() and Graph.__contains__()

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#112]
I'm not sure of the best/usual approach to documenting these, because the dunder methods are called via specific python syntax. But these are definitely intended to be part of the API.

**Comment by jeromekelleher** [comment]
This is probably done as part of an "API Quickstart" section or something, which goes through a quick example of using the Python API, illustarting these features. 

Formally, I guess the best place to document dunder methods like this is in the class docstring, where we list the behaviour on ``==``, ``in``, etc.
