### ISSUE TITLE
remove Graph.asdict_compact()

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#127]
It's horrible and I don't want to make changes to it. Also, it should be called `asdict_simplify()` as per #121. Rather than building the dictionary up from scratch, the implementation should be to call `Graph.asdict()` and then simplify that dictionary.

**Comment by grahamgower** [comment]
On second thought... Maybe we can just remove this method altogether, and only ever provide fully-qualified output? Probably I originally wrote this method to go from the python API back to a simple-ish YAML file. I think maybe that's not a use case we need to support.

**Comment by jeromekelleher** [comment]
I agree we should remove this unless we have a use-case for it. Going from "simple" (not sure that's the right word) to fully-qualified is much easier than the other direction.

**Comment by apragsdale** [comment]
So I know this was already closed and the `asdict_compact()` method remove - but I do think that we still want to support outputting a demes graph in simplified format. We've mostly been thinking about how you go from a YAML description written by a human to the internal representation that can be passed to simulators. But we also have the goal of this being a package that simulation engines import and use as a format for specifying models, and I think it's a bit hard to predict how other software might use it. I can easily imagine wanting to output some generation model in human-readable YAML format. Graham's example of programatically generating some tens of thousands of graphs in an ABC framework and writing/compressing them comes to mind, or a moments/dadi method that optimizes over some parameters of the graph and wants to output it.

The current implementation was a bit of a mess, but with the schema/rules/vocabulary more set now, I think it can be cleaned up and modularized quite a bit and will still be quite useful in the long run.

**Comment by jeromekelleher** [comment]
Fair enough @apragsdale. I'm not sure the storage difference from an ABC simulation would be significant, though - compression algorithms are good at finding repetitive bits of text, and the outputs would always want to be compressed (I would have thought).

**Comment by grahamgower** [comment]
Sorry @apragsdale. :(

Here's an alternative implementation I was playing with before I rage quit.
```python
    def asdict_simplified(self):
        """
        Return a simplified dict representation of the graph.
        """
        data = self.asdict()
        for deme in data["demes"]:
            if math.isinf(deme["epochs"][0]["start_time"]):
                del deme["epochs"][0]["start_time"]
            if deme["epochs"][-1]["end_time"] == 0:
                del deme["epochs"][-1]["end_time"]

            for j, epoch in enumerate(deme["epochs"]):
                if epoch["initial_size"] == epoch["final_size"]:
                    del epoch["final_size"]
                if epoch["size_function"] in ("constant", "exponential"):
                    del epoch["size_function"]
                if j != len(deme["epochs"]) - 1:
                    del epoch["end_time"]

            if len(deme["epochs"]) == 1 and "size_function" not in deme["epochs"][0]:
                deme.update(**deme["epochs"][0])
                del deme["epochs"]

            if "ancestors" in deme and len(deme["ancestors"]) == 1:
                del deme["proportions"]

        # collapse pairwise symmetric migrations
        if "migrations" in data:
            symmetric = []
            asymmetric = data["migrations"]["asymmetric"].copy()
            for migration in data["migrations"]["asymmetric"]:
                source = migration["source"]
                dest = migration["dest"]
                time_lo, time_hi = self._check_time_intersection(source, dest, None)
                if migration["end_time"] == time_lo:
                    del migration["end_time"]
                if migration["start_time"] == time_hi:
                    del migration["start_time"]
                opposite = copy.deepcopy(migration)
                opposite["dest"] = source
                opposite["source"] = dest
                if opposite in asymmetric:
                    asymmetric.remove(migration)
                    asymmetric.remove(opposite)
                    sym = dict(
                        demes = [dest, source],
                        **opposite
                    )
                    del sym["source"]
                    del sym["dest"]
                    symmetric.append(sym)

            if len(symmetric) > 0:
                data["migrations"]["symmetric"] = symmetric
            if len(asymmetric) == 0:
                del data["migrations"]["asymmetric"]
            else:
                data["migrations"]["asymmetric"] = asymmetric

        return data
```

**Comment by apragsdale** [comment]
> Fair enough @apragsdale. I'm not sure the storage difference from an ABC simulation would be significant, though - compression algorithms are good at finding repetitive bits of text, and the outputs would always want to be compressed (I would have thought).

That's probably very true, so maybe not a great use case for why it would be important. I was thinking more of the scenarios where you want to take a best fit model, or best-fit or median model, and also output it in human-readable format. The large amount of repetition really cuts down on the human readability (even within python, you can see a huge difference in the size of the printed `asdict()` vs `asdict_compact()` output).

> Here's an alternative implementation I was playing with before I rage quit.

Sorry Graham, that sounds frustrating! I think I have some responsibility for making that old `asdict_compact` code the huge messy pile that it was... maybe we can leave #128 as is, and I can play around with what you started here to see if it's salvageable and whether the code comes out clean and we want to bring that functionality back in?

**Comment by grahamgower** [comment]
> Sorry Graham, that sounds frustrating! I think I have some responsibility for making that old `asdict_compact` code the huge messy pile that it was... maybe we can leave #128 as is, and I can play around with what you started here to see if it's salvageable and whether the code comes out clean and we want to bring that functionality back in?

Definitely not your fault, as I wrote the original mess. You're welcome to play with that code, and I'd be happy to see something workable go back in. But it might first be worth us thinking about which specific transformations we allow for going between `simplified` and `fully-qualified` graphs.

In particular, we may wish to change the semantics of dealing with `start_time` for a deme versus for the first/last epochs. Inserting epochs between the deme's `start_time` and the first specified epoch is a bit weird when you also consider that the deme's `start_time` can be inferred to be the deme's ancestor's `end_time`. The edge cases make this possibly confusing, rather than being a neat convenience.

**Comment by apragsdale** [comment]
> In particular, we may wish to change the semantics of dealing with `start_time` for a deme versus for the first/last epochs. Inserting epochs between the deme's `start_time` and the first specified epoch is a bit weird when you also consider that the deme's `start_time` can be inferred to be the deme's ancestor's `end_time`. The edge cases make this possibly confusing, rather than being a neat convenience.

Yes - I think you're right about the confusion of inserting epochs when there is a gap. I think the scenario I was thinking about with that is when a deme's start time is inf, but we only start listing epochs with the first size change or something, so it fills that in. We probably just want to say that that first "steady-state" epoch from inf to first event needs to be specified.

I am a fan of keeping the current approach of requiring epoch end times to be specified and the start times implied - I think it makes the distinction between a split event and a branch event much more natural, for example. It also means that in most cases we won't need to write "inf" in the simplified YAML because it will be implied for the start time of a deme with no ancestors if the start time is not given, removing most confusion about writing "inf" vs ".inf" (#130).

**Comment by jeromekelleher** [comment]
> That's probably very true, so maybe not a great use case for why it would be important. I was thinking more of the scenarios where you want to take a best fit model, or best-fit or median model, and also output it in human-readable format. The large amount of repetition really cuts down on the human readability (even within python, you can see a huge difference in the size of the printed asdict() vs asdict_compact() output).

That's a much better motivation! Yes, you're right, we want this.

However, I'd suggest we nail down the semantics elsewhere first, and then return to this problem?

**Comment by grahamgower** [comment]
Closing this as #138 put the functionality back in.
