### ISSUE TITLE
restrict the allowable format for deme IDs

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#136]
Currently we allow just about anything. But this is likely a bad idea. E.g. I can imagine calling my deme ".inf" from the python API, and then after writing it to the yaml, the `id` might be parsed back in as a float. More generally though, deme IDs are probably going to be copied into unexpected places (I bet someone will put them into a filename), so we should be conservative here. Maybe we should check against a regex ike `[-_a-zA-Z]([-_a-zA-Z0-9])*`? Any reason to permit non ascii, or other symbols?

**Comment by jeromekelleher** [comment]
I'm fairly strongly of the opinion we should enforce that they be valid Python identifiers, so that we can do things like pass in deme IDs as keyword args to functions. I don't think it's too restrictive, and people *will* do crazy things unless we specify and enforce this.

WRT to unicode, :shrug:, hard to know what's best to do. I can see models being more portable across different simulators etc if people stick to utf8, but I'm not sure we want to get into specifying encodings.

**Comment by grahamgower** [comment]
Enforcing them to be a valid python identifier is a great idea! [`isidentifier`](https://docs.python.org/3/library/stdtypes.html#str.isidentifier) makes this really easy to check too. This would remove hyphens from the allowable character set, but I'm ok with that.

I don't think we need to deal with encoding issues. YAML and JSON should deal with that (I think I saw UTF8 was the default somewhere). In any event, I'd be comfortable marking any more general unicode bug reports as "will not fix" if the fix is not completely trivial.

**Comment by grahamgower** [comment]
> so that we can do things like pass in deme IDs as keyword args to functions.

Just FYI, I could start naming my test demes `self`, just to make life hard. :)

**Comment by jeromekelleher** [comment]
Good, glad you agree on the identifier thing. I didn't know about ``isidentifier``, that's really handy. We **could** disallow keywords, but maybe that's making us too Python centric? A Python identifier is a fairly universal definition of what an identifier looks like in a reasonable language, but disallowing things like ``lambda`` may be a step too far? I could be convinced either way.

**Comment by jeromekelleher** [comment]
Let's think this through. Code that uses deme IDs as kwargs is nearly always going to be written to support particular models. So, things like ``demography.sample(AFR=3, EUR=2)`` (downstream in msprime) is in a script that knows it's processing a particular family of models.

Where things might break, is if a user does ``**`` expansion on a dictionary of deme IDs. I guess all we can do there is provide better ways of doing the things you might want to do with ``**``, and recommend against it.

**Comment by grahamgower** [comment]
I think we can just restrict to identifiers in `demes`, and be slightly stricter in downstream packages (e.g. warn when loading a model with a keyword deme id in msprime, and disallow inclusion of models with such deme ids for models that live in stdpopsim).
