### ISSUE TITLE
Enforce root deme start times to be inf

### ISSUE THREAD

**Issue by apragsdale** [popsim-consortium/demes-python#169]
Currently, `demes` allows a start time of a deme to be any value >0, even when that deme has no ancestors (i.e. is a root). This implies that some set of individuals spontaneously appear at that deme's start time. We would want to enforce that the first epoch for a deme with no ancestors has a start time of inf.

Edit: I don't think this is a bug (we could think of some experimental evolution scenario where maybe it "makes sense"), but it probably is more confusing than helpful to allow root demes to have finite start times.

**Comment by grahamgower** [comment]
This also suggests a nice and trivial `roots()` method for the graph.
```python
def roots(self):
    return [deme.id for deme in self.demes if math.isinf(deme.start_time)]
```

**Comment by jeromekelleher** [comment]
Well, there's also ``roots = deme.id for deme in self.demes if len(deme.ancestors) == 0]``?

**Comment by grahamgower** [comment]
Yeah, that's probably clearer, and works already.

**Comment by jeromekelleher** [comment]
Depending on ``inf`` semantics always makes me nervous!
