### ISSUE TITLE
make successors and predecessors functions instead of properties?

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#173]
I've been thinking about graph operations today, and it seems like we can convert to `networkx` via:
```python
import networkx as nx
import demes
g = demes.load("some-graph.yml")
gs = nx.from_dict_of_lists(g.successors, create_using=nx.DiGraph)
gp = nx.from_dict_of_lists(g.predecessors, create_using=nx.DiGraph)
```
This is very nice, and gets users immediate access to DAG traversals, transitive closure, etc. from `networkx`. There are two things worth noting here though.
 1. The networkx graphs give a time-agnostic view of the deme relationships.
 2. Pulses and migrations are not edges in these graphs.

If we made successors/predecessors functions, then we could add argument(s) to include pulses/migrations. I'm not sure about the forwards-in-time view (successors) with pulses/migrations added, but the backwards-in-time view (predecessors) of the ancestry is probably very useful. Combining this with a `prune()` operation (which uses/modifies time fields), should be very powerful.

**Comment by apragsdale** [comment]
Sounds great to me, Graham. I like that idea of being able to find successors and descendents either with or without the migrations and pulses, and then `networkx` gives us a ton of built-in functionality to ask about components, roots, etc....

**Comment by jeromekelleher** [comment]
Let's not have a dependency on ``networkx``, if we can help it. I guess we could include it as an ``extras`` if we needed to?

**Comment by grahamgower** [comment]
I don't think we need to depend on `networkx`. Exporting is quite easy, as shown above. It should be more than sufficient to have some example code in a tutorial/vignette that shows some cool stuff using `nextworkx`. E.g. given two samples (two deme/time pairs), find all unique coalescent paths between them.
