### ISSUE TITLE
drop python 3.6 support?

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#180]
Reasons in favour of dropping Python 3.6 before our first release:
 * Python 3.6 is in maintenace mode and will reach "end of life" this year, with only security fixes being considered for the final patch release scheduled for December 2021 (https://www.python.org/dev/peps/pep-0494/).
 * We'll drop support in the future anyhow.
 * Python 3.7 supports dataclasses, which can replace attrs, thereby reducing the number of dependencies. This will facilitate some convergence between the Demes reference implementation in the spec repo and the officially supported demes-python implementation.

Reasons against dropping Python 3.6:
 * This enforces a minimum version on any users of Demes. In particular, this may make developers reluctant to introduce a demes-python dependency.
 *  attrs works, and there's no immediate reason to convert to dataclasses (development effort would be better spent elsewhere).

So, on balance, I'm in favour of keeping python 3.6 support for our first release(s).

**Comment by jeromekelleher** [comment]
Agreed, let's keep py36

**Comment by molpopgen** [comment]
Also, data classes don't really replace attrs, right?  The latter gives validators, easy conversion to dict, etc..

**Comment by grahamgower** [comment]
Yeah, there's some stuff that attrs does quite nicely that dataclasses doesn't have. But probably nothing really essential for us (we could implement things slightly differently).

**Comment by grahamgower** [comment]
We have multiple downstream applications that want Python 3.6 support, so we'll likely keep this for the forseeable future.
