### ISSUE TITLE
recent tests workflow failures with moments on python 3.9

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#196]
Not sure what's going on here, but there are failures evident in today's dependabot PRs. I thought they were due to having multiple numpy versions installed, so opened #195 to fix that. But there's something else going on which is not at all obvious.

I can reproduce the test failures locally, after installing moments via
```pip install git+https://bitbucket.org/simongravel/moments@moments-1.0.8#egg=moments```.
However, the failures don't occur after installing moments from a locally cloned repository with `python setup.py install --user`.

**Comment by grahamgower** [comment]
The problem here is related to something called "build isolation" during `pip install`. Essentially, when you call `pip install foo`, pip will create an isolated environment with the packages listed in foo's `build_requires`. This ignores any current environment the user has installed. So in the case of pip-installing moments, we end up with pip installing numpy into the isolated environment, and pip resolves this to the *latest* numpy version, ignoring the currently installed numpy. Now, numpy 1.20.0 was recently released, with a backwards-incompatible binary API change. So pip builds moments against numpy-1.20.0 in the isolated environment, and then we try to use moments in our target environment with numpy-1.19.x.

I expect that reports of the following error will be widespread over the next few days, because there are going to be a *lot* of projects encountering this problem.
```
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

There's a bunch of discussion here about the general problem. I'm not convinced the suggestions are foolproof, so I guess we'll see how other projects deal with this in the coming days.
https://discuss.python.org/t/pep-517-how-to-pick-compatible-build-dependencies/2460/2

**Comment by apragsdale** [comment]
Hi @grahamgower thanks for catching this. It's definitely not something I had run into before, but something that does need to be fixed in the `moments` distribution.

On another note, I wonder if it's time to remove the moments conversion from demes itself. I've copied it to a branch for a future release within `moments` and update and test it there as well. Dropping it here will simplify things as we gear up for our alpha release when we'll remove the built-in conversion methods (except maybe for old `ms` command line code).

**Comment by grahamgower** [comment]
> On another note, I wonder if it's time to remove the moments conversion from demes itself. I've copied it to a branch for a future release within `moments` and update and test it there as well. Dropping it here will simplify things as we gear up for our alpha release when we'll remove the built-in conversion methods (except maybe for old `ms` command line code).

I suspect there are still going to be API changes, unfortunately. E.g. #188 already touched the moments and moments test code. If you're willing to forgo getting those fixes as the API is changed, then by all means, we can remove the moments code from Demes.

**Comment by apragsdale** [comment]
Yeah, let's go ahead and just remove the moments conversion. I already have it integrated within the next moments release branch, so it doesn't make sense to maintain that code both there and here, and it's going to be living there eventually. I don't mind maintaining it as the API changes in the coming weeks.
