### ISSUE TITLE
`in_generations` does not convert `deme[id].start_time`

### ISSUE THREAD

**Issue by apragsdale** [popsim-consortium/demes-python#224]
If we have a deme graph in years, for example, and call `g_gen = g.in_generations()`, the resulting deme graph `g_gen` does not properly convert deme start times.

For example:

```Python
import demes
file_in = "examples/gutenkunst_ooa.yml"

g = demes.load(file_in)

print(g["AMH"].start_time)
print(g["AMH"].epochs[0].start_time)

g_gen = g.in_generations()

print(g_gen["AMH"].start_time)
print(g_gen["AMH"].epochs[0].start_time)

# note that there is no issue with end time, because
# of the end_time function grabbing the last epoch's end time
print(g_gen["AMH"].end_time)
print(g_gen["AMH"].epochs[0].end_time)
```

I _think_ this is just a quick fix of updating the `in_generations` function to also set `deme.start_time /= generation_time`, but @grahamgower maybe there is something more subtle going on?

**Comment by grahamgower** [comment]
Nice catch! I think this just got forgotten when `Deme.start_time` got promoted from a `@property` to an attribute. It does make me a little suspicious that the test for `in_generations()` isn't doing what it should though.

**Comment by apragsdale** [comment]
Yeah, I noticed this when converting a graph in years to generations and then getting the list of discrete demographic events, which said everything was a branch instead of splits and was causing errors in the moments implementations using demes. Took a bit of tracking down to find the culprit, and it's not an obvious issue, so not surprised it was missed.

I guess multiple alpha releases isn't a problem, so we can quickly fix this and put out a new alpha release?

**Comment by grahamgower** [comment]
> I guess multiple alpha releases isn't a problem, so we can quickly fix this and put out a new alpha release?

Absolutely! An alpha a day keeps the stable release away?

**Comment by grahamgower** [comment]
> It does make me a little suspicious that the test for `in_generations()` isn't doing what it should though.

And it looks like `Deme.start_time` was also omitted from the `Deme.assert_close()` function, upon which the test relies.
