### ISSUE TITLE
version string in the docs looks wrong

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#226]
Looks right on my local machine (shows `0.1.0a3`), but the CI docs build shows the following:
![version](https://user-images.githubusercontent.com/8665077/109129854-5eb66480-7751-11eb-8c09-219e8b3ef128.png)

**Comment by jeromekelleher** [comment]
This is a persistent problem I've had with RTD - never figured out how to fix it.

**Comment by jeromekelleher** [comment]
Oops, this isn't rtd!

This looks like a "shallow" clone, and the tag info isn't available for setuptools_scm.

**Comment by grahamgower** [comment]
I think this is just showing a version string when the commit was merged into `main`. I'm tagging the release after this, and there's probably no CI trigger for tags. But maybe you're right, and something else is going on too. :shrug:

**Comment by jeromekelleher** [comment]
I can't remember which repo it was on, but I definitely hit [this issue](https://github.com/pypa/setuptools_scm/issues/414) somewhere. The fix was simple, I think it was just setting the depth to 0 or something.

**Comment by grahamgower** [comment]
Yep, #228 did the trick, thanks @jeromekelleher!
