### ISSUE TITLE
add __str__() and _repr_html_() methods for the Graph, Epoch, et al.

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#235]
So that we do better than, e.g.:
```python
Graph(description='asymmetric migration between two extant demes', time_units='generations', generation_time=None, doi=[], demes=[Deme(id='X', description=None, start_time=inf, ancestors=[], proportions=[], epochs=[Epoch(start_time=inf, end_time=1000, start_size=5000, end_size=5000, size_function='constant', selfing_rate=0, cloning_rate=0)]), Deme(id='A', description=None, start_time=1000, ancestors=['X'], proportions=[1.0], epochs=[Epoch(start_time=1000, end_time=0, start_size=5000, end_size=5000, size_function='constant', selfing_rate=0, cloning_rate=0)]), Deme(id='B', description=None, start_time=1000, ancestors=['X'], proportions=[1.0], epochs=[Epoch(start_time=1000, end_time=0, start_size=5000, end_size=5000, size_function='constant', selfing_rate=0, cloning_rate=0)])], migrations=[AsymmetricMigration(start_time=1000, end_time=0, rate=0.0001, source='A', dest='B')], pulses=[])
```
Like recently added to msprime's Demography class.

**Comment by jeromekelleher** [comment]
I'm really missing a proper ``str`` implementation when working with demes - any thoughts on what this should look like? Even a simple tabular output would be very helpful.

**Comment by grahamgower** [comment]
The attrs default leaves a lot to be desired. There's an example here using the `prettyprinter` package which looks nice: https://github.com/python-attrs/attrs/issues/508#issuecomment-465891801

**Comment by jeromekelleher** [comment]
I think I'd be better to just hand craft something - it's time well spent, as it makes debugging so much easier.

**Comment by grahamgower** [comment]
It turns out that it's possible to output a mix of flow style and block style using ruamel.yaml. I haven't quite figured out the incantation to do so, but if we can output deme ancestors/proportions and epochs/migrations/pulses using the flow style, this will certainly make for compact and readable debug output.
