### ISSUE TITLE
generate random input graphs, for testing

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#24]
The structure for the yaml file is reasonably settled now, so it shouldn't be too hard to generate random files.

**Comment by grahamgower** [comment]
We're going to load YAML and JSON into data dictionaries, and that data object will instead be validated from a JSON schema. Here are some utils for using the schema for testing and other interesting stuff.
https://json-schema.org/implementations.html#generators-from-schemas
https://github.com/Zac-HD/hypothesis-jsonschema
https://metacpan.org/release/JSON-Schema-ToJSON

**Comment by jeromekelleher** [comment]
> https://github.com/Zac-HD/hypothesis-jsonschema

Very cool! That would be an excellent fuzz-testing tool for our schema.
