### ISSUE TITLE
Use setuptools' extras_require?

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#240]
This underdocumented feature of setuptools allows one to have different flavours of a python library, each with different dependencies. I'm not so sure of the caveats of using it, though I suspect it won't be a good fit for us. In any event. here's an example to give an idea.

We could have `extras_require={"draw": ["matplotlib", "scipy"]}`. Then `pip install demes` does the normal thing, without a dependency on matplotlib or scipy. But `pip install demes[draw]` pulls in the extra dependencies (and somehow enables additional functionality: possibly as simple as allowing one to `import demes.draw`).

Honestly, I think this is around the wrong way though. Really, we want projects like `moments`, `msprime`, `fwdpy11` to depend on `demes[minimal]` (the smallest set of dependencies), but have users install `demes` (with the full complement of useful extras). But I don't think this organisation is supported by setuptools/pip/pypi. At least, it's very difficult to figure this out because of lack of documentation.

EDIT: seutptools have updated their docs recently, see here: https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies

**Comment by grahamgower** [comment]
If we decide not to do this for `demes` pypi package, then we could create a separate repository and pypi package where we are very liberal about incorporatig various "extras".

**Comment by jeromekelleher** [comment]
It's always a compromise all right. I'd have no problem with 

```
pip install demes
```
giving the bare-bones installation that other packages can depend on, and 
```
pip install demes[all]
```
throwing in the kitchen sink.

Remember that we need to package in conda as well, but I guess the approach there would be to always package the full "all" installation.

**Comment by molpopgen** [comment]
This is worth keeping in mind.  I agree that simulation software, etc., probably wants to only depend on a minimal setup.

**Comment by grahamgower** [comment]
After some reflection, I've decided that I don't want to use `extras_require`. What we really want, is a default "extra", but that isn't supported (see [this long discussion that goes nowehere](https://discuss.python.org/t/adding-a-default-extra-require-environment/4898)). Using optional extras as they're intended, and then telling users to, e.g. `pip install demes[all]`, seems like a bad idea.

There will always be some user who got `demes` installed because it's a dependency, or just plain installed it without the `[all]` key, and also happens to have installed an old version of one of the extras_require packages. So either (1) we have to give support when things fail mysteriously or give subtley different behaviour, or (2) we have minimum required versions in the setup.cfg as well as wherever the dependency is `import`ed. Neither option seems appealing.

I'm still coveting the `demes.draw` namespace though. :(

**Comment by jeromekelleher** [comment]
Plugins?

**Comment by grahamgower** [comment]
> Plugins?

I didn't know about that. I'll take a closer look and see what it would look like...
