### ISSUE TITLE
enforce an upper bound for the migration rate

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#244]
Once we know what units we're using, we should be able to figure out the upper bound. https://github.com/popsim-consortium/demes-spec/issues/21

**Comment by molpopgen** [comment]
There's a long history in the theoretical literature defining migration rates as ancestry proportions.  Freddy Christiansen's papers, Malecot, etc..

**Comment by grahamgower** [comment]
Sorry, I'm still being dense. Does this mean we should use big `M` (so our upper bound is 1) or little `m` (our upper bound is the ratio of population sizes) from https://tskit.dev/msprime/docs/latest/demography.html#definitions ?

**Comment by molpopgen** [comment]
So it means they are fractions.  I guess lower case m, where mij is the proportion of deme j whose ancestry is from deme i, meaning their parents were drawn from i.

**Comment by molpopgen** [comment]
I'm assuming the denominator is "per generation", which I should be explicit about.

**Comment by apragsdale** [comment]
I think what we’d want is that the sum of incoming migration rates/probabilities is bounded by one, since I think like Kevin said we want to think of these as probabilities of ancestry proportions each generation. That’s maybe a bit trickier to check because we allow epochs of migration and would need to loop through the migrations somehow.

**Comment by grahamgower** [comment]
Does this mean we don't need to change anything except to enforce `migration.rate <= 1`? Can we just do that, and let downstream simulators enforce that `sum(matrix_row)<=1`?

And clearly someone who isn't me needs to write the docs on this stuff!

**Comment by molpopgen** [comment]
> Does this mean we don't need to change anything except to enforce `migration.rate <= 1`? Can we just do that, and let downstream simulators enforce that `sum(matrix_row)<=1`?
> 
> And clearly someone who isn't me needs to write the docs on this stuff!

Ideally, we'd somehow loop through the migration matrix over time and assert that row sums are 1.  That check should be redundant to what a simulator does, but it'd be user friendly to catch at the YAML/graph stage.

**Comment by grahamgower** [comment]
Ok, thanks for the input! Here's what I'm taking away from this:
1. The way we're *using* migration rates in demes is currently consistent with expected ancestry proportions per generation (inasmuch as we don't convert units when going to/from msprime and moments). And we want to keep it this way.
2. A "continuous" migration spanning one generation is equivalent to a pulse, if they have the same rate/proportion and source/dest.
3. We really should construct migration matrices and enforce the upper limit properly. This should be fine, as there's already code to make the migration matrices inside `demes.convert.to_msprime()`.
4. In light of 3., we might consider exporting a migration matrix generating function in the API (but this is low priority).

**Comment by molpopgen** [comment]
Yeah, this sounds right.  The equivalence to a pulse is an interesting thing for the simulators to wrestle with, in terms of what they do w/a demes Graph.

**Comment by grahamgower** [comment]
Cool. I should have clarified that I'd only expect migration/pulse equivalence for discrete-time simulation.
