### ISSUE TITLE
codecov only giving reports for every second PR

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#248]
At least, that seems to be the pattern. Any idea what would cause that @jeromekelleher?

**Comment by jeromekelleher** [comment]
Nope, not a clue. Codecov can be mysterious

**Comment by grahamgower** [comment]
There's no pattern. Looking at the codecov dashboard for [demes-python](https://app.codecov.io/gh/popsim-consortium/demes-python), many recent commits show "Unable to find commit in Github". Apparently this is caused by codecov being rate limited by github, and "installing the codecov github app" is a workaround (https://community.codecov.io/t/unable-to-find-commit-in-github-in-the-recent-dashboard/1145/4). I poked some settings in some mysterious location that lives between github and the codecov marketplace, and the installation for this repository is now marked as "[request]". I guess that means someone will get a notification and rubber stamp it? Not sure if that is something in github, codecov, or popsim-consortium.

**Comment by jeromekelleher** [comment]
I've approved the request.

**Comment by grahamgower** [comment]
Thanks!
