### ISSUE TITLE
Make `demes` a namespace package (as well as a regular package)

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#252]
This is an alternative proposal to #240, and aims to facilitate direct integration of demes-related packages. Concretely, this would allow `demes` to maintain a minimal dependency footprint while allowing an external "demes-draw" package to use the `demes.draw` namespace. To do this, demes-draw would need to be a "namespace package", structured as follows:
```
toplevel-demes-draw-folder/
    README.md
    setup.cfg
    ...
    demes/
        draw/
            __init__.py
            ...
```

By convention, the "demes.draw" namespace package would have a pip-installable package name of "demes-draw". This actually works fine already, assuming that both `demes` and `demes-draw` are installed into the same location with pip. However, this will break if they are installed into different locations (common examples given below). To make this work when `demes` is installed in a different location to the (other) namespace packages, `demes` must also become a namespace package. The diff below indicates a small (but possibly obscure) change to `demes` that would make it a "regular package" and a "namespace package" simultaneously.

```diff
diff --git a/demes/__init__.py b/demes/__init__.py
index 1ef84fd..7b57033 100644
--- a/demes/__init__.py
+++ b/demes/__init__.py
@@ -23,3 +23,31 @@ from .demes import (
     Admix,
 )
 from .load_dump import load_asdict, loads_asdict, load, loads, dump, dumps
+
+# To allow namespace packages using the `demes` namespace, e.g. `demes.draw`,
+# `demes` must also be a namespace package. We achieve this below by
+# extending __path__.
+# This is required when `demes` is installed in a different directory to the
+# namespace package, and tells the import machinery to continue looking under
+# additional directories (after `demes` is found) for namespace packages.
+#
+# Example 1.
+#   `demes` is in: /usr/lib/python3.9/site-packages/demes
+#   `demes.draw` is in: $HOME/.local/lib/python3.9/site-packages/demes/draw
+#
+# Example 2.
+#   `demes` is in: $HOME/.local/lib/python3.9/site-packages/demes
+#   `demes.draw` is being developed under the current directory: ./demes/draw
+#
+# Without the extension to __path__ below, calling "import demes.draw" would
+# fail, because `demes` is first imported, and no other directories are
+# searched for the `demes.draw` namespace.
+#
+# See:
+# https://www.python.org/dev/peps/pep-0420/
+# https://packaging.python.org/guides/packaging-namespace-packages/
+# https://docs.python.org/3/reference/import.html#module-path
+# https://docs.python.org/3/library/pkgutil.html#pkgutil.extend_path
+from pkgutil import extend_path
+
+__path__ = extend_path(__path__, __name__)  # type: ignore
```

Some preliminary testing indicates this does the right thing. Import time ought to be affected only negligibly. A CLI can even be provided at "python -m demes.draw" by dropping a `__main__.py` in the relevant location. Besides needing to be careful about not having name clashes with "blessed" third-party namespace packages, this seems to work well. The only thing that bothers me is some uncertainty over unintended consequences: I wasn't able to identify any information about this exact thing (using a path extension to make a dual "regular package" / "namespace package" --- all examples I found have an empty `__init__.py` other than the path extension).

Thoughts?

**Comment by jeromekelleher** [comment]
I'm pretty lukewarm on this to be honest. It seems like a lot of complication and confusing plumbing for something that's a very marginal benefit (just so we can call it ``demes.draw``, right?).

Why not make a separate package called ``demesdraw`` or ``demesviz`` and be done with it?

**Comment by grahamgower** [comment]
Yeah, fair enough. I suppose I was just exploring the confusing landscape that is python packaging. A separate package, with a separate name is fine too.
