### ISSUE TITLE
nail down semantics for many-deme symmetric migrations

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#263]
The semantics for many-deme symmetric migrations are not clear. https://github.com/popsim-consortium/demes-spec/issues/55. I'm leaning towards making this an error as Jerome suggests in the spec issue. There are probably some tricky details to be worked out here, with regard to the `Graph.asdict_simplified()` code --- I yanked out the migration simplification code again a few weeks back (sorry Aaron!), in part because it didn't fit with the splitting into two migration classes, but also because of the lack of clarity here. It would be really great to have the migration simplification code back.

**Comment by jeromekelleher** [comment]
I think at this point we should err on the side of simplicity - anything we can do without in the initial version that we're not 100% happy with, just take it out. It's easy enough to update a spec later with extra things, but it's hellishly hard to change things that are slightly wrong.

**Comment by jeromekelleher** [comment]
(By leave out, I mean make it an error. It's OK to make something that used to be an error condition have well defined semantics, less OK to go the other way around)

**Comment by grahamgower** [comment]
Yep, I agree that this is the most reasonable step to take. So to be concrete: for symmetric migrations where the migration `start_time` (or `end_time`) isn't specified, then all participating demes *must* have the same `start_time` (or `end_time`), otherwise an error is raised.

This will, unfortunately, lead to some repetition of time values for some models. E.g. the following will be an error, as the migration should also have `start_time: 100`.
```yaml
time_units: generations
defaults:
  epoch: {start_size: 1000}
demes:
  - name: A
  - name: B
    ancestors: ["A"]
    start_time: 100
migrations:
  - demes: [A, B]
    rate: 1e-5
```

**Comment by apragsdale** [comment]
> E.g. the following will be an error, as the migration should also have `start_time: 100`.

Hmm, I don't really like that.. Can we check that start/end times align only when _more_ than two demes are involved in the migrations? Otherwise, that's a pretty tedious condition for specifying the demography.

**Comment by grahamgower** [comment]
> Hmm, I don't really like that.. Can we check that start/end times align only when _more_ than two demes are involved in the migrations? Otherwise, that's a pretty tedious condition for specifying the demography.

I think having different rules for n-way migrations when n=2 compared to n>2 is probably a misstep. Perhaps we really do want to do pairwise resolution of n-way symmetric migrations? In this scheme, each n-way migration without a `start_time` (or `end_time`) is "resolved" by breaking it into multiple pairwise migrations with `start_time=min(deme1.start_time, deme2.start_time)` (or `end_time=max(deme1.end_time, deme2.end_time)`). `demes-python` had this behaviour last year.

The resolution process is simple enough, but only if we don't try to maintain n-way symmetric migrations after resolution---the simplest thing to do is to resolve everything into asymmetric migrations (which we were doing previously). So I guess the Python API here would really need to supply both "sparse" (list of asymmetric migrations) and "dense" versions (list of migration matrices). Having a `SymmetricMigration` class internally actually introduces more complexity (e.g. https://github.com/popsim-consortium/demes-python/blob/main/demes/demes.py#L1342-L1363, #216). Aaron's excellent migration simplification code can then be put back into `asdict_simplified()` almost verbatim.

**Comment by jeromekelleher** [comment]
Sounds reasonable to me @grahamgower - saying that symmetric migrations are really just a thin wrapper around the pairwise asymmetric migrations is a good way of reducing complexity.
