### ISSUE TITLE
change to slotted attrs classes

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#276]
These are more memory efficient, which should be a win if anyone wants to make millions of graphs or something. There are some side effects though, which might be considered advantages or disadvantages, depending on your point of view.
* Multiple inheritance isn't allowed.
* It's not possible to add attributes to an exiting object. E.g. `graph = demes.load(...); graph.mutation_rate = 1e-8` would be an error. This shouldn't be a problem if we have a `metadata` dict inside each class.
* If we use slots and then decide we don't want them, we can change to non-slotted later. If we start with non-slotted classes and later decide we want them, this is a breaking change (because of the previous two points).

I'm leaning towards changing over to slotted classes before 0.1.0 (it's a trivial change), but could be convinced not to. Anyone have a strong opinion?

**Comment by molpopgen** [comment]
I'm okay with this.  I there a reason to prefer attr over data classes here?  I make a lot is use of features specific to attr, but they may not matter here?

**Comment by grahamgower** [comment]
Actually, slotted arguments are a strong reason to stick with attrs. While it's possible to use slots with Python 3.7+ dataclasses, one has to manually add the `__slots__` attribute to the class (there's no slots=True option for the decorator, and python devs don't have plans to remedy this). And in the later case, manually adding slots to a dataclass doesn't work with default values. It turns out that attrs is pretty damn nice after all!

**Comment by grahamgower** [comment]
Attrs have a useful description of slotted classes:
https://www.attrs.org/en/stable/glossary.html#term-slotted-classes

Discussion on why dataclasses doesn't make it easy to use slots:
https://github.com/ericvsmith/dataclasses/issues/28

**Comment by jeromekelleher** [comment]
Sure, happy to use slots.
