### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-python#280]
It would be good to have a conda-forge package for demes - any objections? I can take care of it.

**Comment by grahamgower** [comment]
That would be amazing, thanks @jeromekelleher!

**Comment by molpopgen** [comment]
This is kinda necessary--moments and fwdpy11 both cannot be updated until there is one.  Thanks Jerome!

**Comment by jeromekelleher** [comment]
OK, will report back.

**Comment by jeromekelleher** [comment]
In progress: https://github.com/conda-forge/staged-recipes/pull/14656

**Comment by jeromekelleher** [comment]
https://github.com/conda-forge/demes-feedstock

https://anaconda.org/conda-forge/demes
