### ISSUE TITLE
add proper CLI

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#282]
We should consider what features we want from a demes CLI, and how we expect folks to use it. Probably format conversion would be most useful. Maybe some options like:
```
usage: python -m demes [-s] [-f] [-y] [-j] [input.yaml | input.json]  > output.format

-s --simplified        output simplified model (default for YAML and JSON output)
-f --fully-resolved    output fully-resolved model
-y --yaml              output YAML (default output)
-j --json              output JSON
```

Or maybe also support an `ms` subcommand to convert ms command lines? That will need a mandatory `N0` option to convert units. Maybe that would work better as it's own `python -m demes.ms` command?

**Comment by jeromekelleher** [comment]
Probably better to have some subcommands, I think. I can imagine ``validate`` being a very useful one.
