### ISSUE TITLE
Linear size function

### ISSUE THREAD

**Issue by noscode** [popsim-consortium/demes-python#296]
I have [added demes to GADMA](https://github.com/ctlab/GADMA/commit/911e8e672414038138525f0ccc4e309a8ed78e9a) to use it for the alternative representation of the demographic histories. I also used demesdraw for drawing. I have faced to one problem though. By default, GADMA uses three types of size functions: constant, exponential and linear. Unfortunately, demes does not support linear function right now and GADMA has to print warnings when it try to use demes for the demographic history with linear size change. It is not very big deal but it would be very cool to get support of linear functions.

I found some discussion here #262: additional size function support was planned in the future. What do you think about adding linear now? If you like I can implement it as then GADMA will be able to use demes for any history and I really like it to do so.

**Comment by grahamgower** [comment]
> I have [added demes to GADMA](https://github.com/ctlab/GADMA/commit/911e8e672414038138525f0ccc4e309a8ed78e9a) to use it for the alternative representation of the demographic histories. I also used demesdraw for drawing.

Oh, wow! Cool!

> I have faced to one problem though. By default, GADMA uses three types of size functions: constant, exponential and linear. Unfortunately, demes does not support linear function right now and GADMA has to print warnings when it try to use demes for the demographic history with linear size change. It is not very big deal but it would be very cool to get support of linear functions.
> 
> I found some discussion here #262: additional size function support was planned in the future. What do you think about adding linear now? If you like I can implement it as then GADMA will be able to use demes for any history and I really like it to do so.

Yes, this sounds good. It would be great if you could add in the bits needed for `size_function == "linear"`. Probably this doesn't need much, just a few lines plus the tests.

I suppose we should keep the current behaviour where if size_function is not specified in a YAML, but start_size != end_size, then the size_function defaults to "exponential".

Any other thoughts @apragsdale?

**Comment by noscode** [comment]
> I suppose we should keep the current behaviour where if size_function is not specified in a YAML, but start_size != end_size, then the size_function defaults to "exponential".

I agree, I was thinking about the same thing.

**Comment by jeromekelleher** [comment]
This is great - we should update the spec also.

**Comment by grahamgower** [comment]
Closed by #310.
