### ISSUE TITLE
Compute size of deme at time t

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-python#312]
Now that we have linear size functions too (#310), we should add a function that computes the size of a deme at time t (raising a ValueError if the deme doesn't exist at this time).

**Comment by grahamgower** [comment]
We can copy this from `demesdraw` with minor changes.
https://github.com/grahamgower/demesdraw/blob/main/demesdraw/utils.py#L59
https://github.com/grahamgower/demesdraw/blob/main/tests/test_demesdraw.py#L120
