### ISSUE TITLE
`pip install -r requirements.txt` runs forever (or takes longer than I bothered to wait)

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#319]
It seems there's a conflict somewhere in the version requirements. Installing the requirements/*.txt separately works fine, which explains why there's no failure during CI. We should (1) find/fix the version conflict and (2) add a CI step that installs from this requirements file.

**Comment by grahamgower** [comment]
It looks like one of `jupyter-book`'s  dependencies (`markdown-it-py`) wants an older version of attrs. There's a newer version of `markdown-it-py` that relaxes the requirement for attrs<21, but that version is not installed because other dependencies of `jupyter-book` (`jupytext` and `myst-parser`) pin to an older version of `markdown-it-py`. The docs build just fine if you force pip to install the latest `attrs` and the old version of `markdown-it-py`.

I might just leave this as it is and see if it gets resolved with the next batch of dependabot updates next month.

**Comment by molpopgen** [comment]
This one is biting me right now, too.  I'm using `pip-compile` to explicitly pin everything.  It all came crashing down because of this.

**Comment by grahamgower** [comment]
Are you suggesting that the demes' requirements.txt is confusing your use of pip-compile in fwdpy11, or that you're getting the same problem (coincidentally) because of also depending on jupyter-book and attrs?

A workaround would be to pin to `attrs==20.3.0`. Maybe we should do that for a while? This version of attrs gives a deprecation warning with demes (specifically for `attr.ib(..., cmp=False)`), but otherwise works fine. Attrs 21.x has "undeprecated" the `cmp` option.

**Comment by molpopgen** [comment]
I managed to show (I think) that it isn't due to anything in demes.  It seems to be this mess w/jupyter-book.  I just bumped all the attrs down to 20.3.0 and am running tests for that now.

**Comment by molpopgen** [comment]
One irritation, which I think you may also have noted, is that `pip check` fails to find any conflicts once I semi-manually get a working environment in place.

**Comment by molpopgen** [comment]
executablebooks/jupyter-book#1351

**Comment by grahamgower** [comment]
Fixed by #321.
