### ISSUE TITLE
clean up the exported names

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#324]
We should use `__all__` to only export names that are part of the public API. Also see mypy --strict output in #323, where the `Module has no attribute "foo"` suggests where we might consider explicit exports.

**Comment by molpopgen** [comment]
Serious question: is it actually possible to satisfy mypy?  In my experience, every warning or two that I silence seems to open up other cans of worms.

**Comment by grahamgower** [comment]
> Serious question: is it actually possible to satisfy mypy? In my experience, every warning or two that I silence seems to open up other cans of worms.

Scanning the `mypy --strict` output, I think there's a bunch of stuff that could be fixed quite easily. We can just ignore the hard bits. But given that we want demes to be used widely, I think it's worth making some effort to have good type annotations so that downstream projects can benefit from type checking too.

Apart from attrs classes, we're mostly using stock Python types (float, int, str) and simple containers (list, dict, tuple), so annotations for function params and return values shouldn't be too onerous. Of course, typing support is not as good in Python 3.6 as in Python 3.9, so there will be some constraints (e.g. having to say `typing.List[float]` instead of just `list[float]`).
