### ISSUE TITLE
Graph.assert_close() shouldn't ignore pulse ordering.

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#328]
The docs currently say that `the order in which admixture pulses were specified` is ignored during the comparison. But this shouldn't strictly be the case. If multiple pulses are specified for the same time, then the order in which pulses were defined will matter. Hence the correct thing to do is to (stable)sort pulses by the time field and then compare.

**Comment by grahamgower** [comment]
Actually, it might be more tricky that this... The order of pulses with the same `time` value only matters when the pulses have demes in common. E.g. for pulse 1: `source=A, dest=B`, pulse 2: `source=B, dest=C`, the pulse order matters. But in other cases, e.g. pulse 1: `source=A, dest=B`, pulse 2: `source=X, dest=Y`, the order of pulses should be ignored.

**Comment by jeromekelleher** [comment]
Better to be overly strict and require a bit of arbitrary sortedness than to falsely claim equality, IMO
