### ISSUE TITLE
Issue on page /introduction.html

### ISSUE THREAD

**Issue by hyanwong** [popsim-consortium/demes-python#336]
The demes online manual doesn't seem to mention demesdraw anywhere, which seems a missed opportunity.

**Comment by molpopgen** [comment]
It is not stable/released (not on pypi).

**Comment by hyanwong** [comment]
I'm pretty sure it is on PyPI. At least, I just installed it from there and @grahamgower just made a new bug fix release about an hour ago.

**Comment by grahamgower** [comment]
Well, you're both right. :) Its on PyPI, but I'm not prepared to make any stability or backwards-compatibility guarantees.

**Comment by hyanwong** [comment]
We're always both right 😄

**Comment by molpopgen** [comment]
I didn't realize it was on PyPi!  That'll make some requirements.txt files simpler.

**Comment by grahamgower** [comment]
The introduction and quickstart both have demesdraw figures now, with example code.
