### ISSUE TITLE
add validation script that runs simulations and checks different simulators are consistent

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#356]
_Originally posted by @jeromekelleher in https://github.com/popsim-consortium/demes-python/issues/354#issuecomment-877047550_
> I guess we should create an issue to track creating a validation script, like msprime's verification.py? We could run a few representative models though ms and msprime, and see if we get the same distributions of coalescent times etc. Probably the only way to really be sure we're getting this stuff right. There's no point in running ms as part of CI.

Yeah, I was thinking we need something exactly along those lines. Should be easy enough to check the SFS against moments, fwdpy11, etc. What we really need to go along with it though, are a handful of carefully chosen demographic models that will expose differences when there are bugs in the trickiest parts of the conversion process (e.g. asymmetric migration direction, simultaneous pulses).

**Comment by jeromekelleher** [comment]
Sounds good. Simplest way to run the evaluations would be:

- Run ms, and pipe the output into tsconvert [from_ms](https://github.com/tskit-dev/tsconvert/blob/main/tsconvert/newick.py#L29) (tsconvert will go through a release soon, though, and the signature of this function will probably change to taking a file handle/path as input rather than a string)
- Run msprime
- Compare the output tree sequences. QQplots of root times is probably as good a diagnostic as any.

**Comment by molpopgen** [comment]
I have a repo that does a bit of this, and could do much more.  I am still pondering how best to split up the docker bits to modularize the tests.

It makes heavy use of moments.

https://github.com/molpopgen/fwdpy11_statistical_tests

**Comment by grahamgower** [comment]
Great, thanks @molpopgen. I had a feeling you'd done this, but I was having trouble finding it.

**Comment by molpopgen** [comment]
> Great, thanks @molpopgen. I had a feeling you'd done this, but I was having trouble finding it.

I takes a while to run and putting it in a separate repo lets me run it on various branches more easily.

**Comment by grahamgower** [comment]
Added in #354. It needs unreleased version of msprime and tsconvert, so it will likely need modifications the next time someone tries to run it.
