### ISSUE TITLE
change pulse source/proportion to support simultaneous sources in pulse events

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#359]
See https://github.com/popsim-consortium/demes-spec/issues/100 and PR #353.

NOTE: This is a breaking change, so we'll need to coordinate with downstream software.

**Comment by grahamgower** [comment]
I think the best way to manage this breakage is to introduce it in a `0.2.0` release. And we should first give downstream software enough time to make their own point release that pins `demes < 0.2`. Then when we release 0.2.0 it hopefully won't break too many installations.

**Comment by apragsdale** [comment]
Closed by #353
