### ISSUE TITLE
Create Demes--> MaCS translator

### ISSUE THREAD

**Issue by gregorgorjanc** [popsim-consortium/demes-python#487]
MaCS is quite performant in several cases (see https://github.com/tskit-dev/msprime/issues/1651) so having Demes --> MaCS translator would be handy to have. Possibly even MaCS --> Demes (@grahamgower tells me at https://github.com/RacimoLab/demes-r/issues/3#issuecomment-1323573188 that this is pretty complicated though).

All this might be fairly straightforward though because MaCS accepts all? ms arguments!

I would be ok working on this ...

**Comment by grahamgower** [comment]
The ms converter functionality could definitely be reused here, so the effort involved should be quite small. I seem to recall that there were some (small) discrepancies between MaCS cli args and ms args, which we would need to handle carefully. So I think the first steps would be to identify:

* what cli args have different interpretations between MaCS and ms.
* what additional args does MaCS accept that would need to be implemented for a MaCS->Demes translator.

**Comment by grahamgower** [comment]
The proportion of lineages moved via the `-es` option is different to ms. https://github.com/gchen98/macs/issues/34

**Comment by grahamgower** [comment]
Another check worth doing would be to run the following script, setting the MS variable to the path of the macs binary, which checks the interpretation of migration indices. https://github.com/popsim-consortium/demes-python/blob/main/tests/ms_asymmetric_migration.sh

**Comment by gregorgorjanc** [comment]
With the improved scalability of SMC in msprime https://github.com/tskit-dev/msprime/issues/1651#issuecomment-2213327244, msprime is now as fast as MaCS, so not sure we need this anymore, hence closing the issue for now.
