### ISSUE TITLE
Graphs inconsistent w/the specification are accepted

### ISSUE THREAD

**Issue by molpopgen** [popsim-consortium/demes-python#576]
The Python API will accept this graph:

```python
import demes

yaml = """
time_units: generations
demes:
 - name: A
   epochs:
    - start_size: 1000
 - name: B
   epochs:
    - start_size: 1000
 - name: C
   epochs:
    - start_size: 1000
pulses:
- sources: [A]
  dest: C
  proportions: [0.]
  time: 10
"""

g = demes.loads(yaml)
```

The JSON schema of the [specification](https://popsim-consortium.github.io/demes-spec-docs/main/specification.html) excludes 0 as a valid value for a proportion:

```json
  proportion:
    type: number
    exclusiveMinimum: 0
    maximum: 1
```

Some casually grepping of the test cases in the demes-spec repo indicated that 0.0 doesn't appear anywhere over there.  I could have missed it, though.

**Comment by grahamgower** [comment]
Fixed by #577.
