### ISSUE TITLE
keep the documentation as short as possible (but not shorter)

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#62]
`Demes` doesn't really *do* much, so we should be frugal with our words. We should anticipate that most folks will come to the docs because they want to write a yaml format demography to be used with a different project.

**Comment by apragsdale** [comment]
Yeah, I might have gotten a bit carried away with the YAML tutorial and spell out in detail all the various demographic events. I don't think the Python API needs to be so detailed - maybe just for developers - since I imagine most general users will be writing YAML descriptions.

**Comment by grahamgower** [comment]
Closing, as the docs are in pretty good shape.
