### ISSUE TITLE
Codecov: submit coverage reports to get coverage tracking over time

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#71]
It's free for open source projects, we just need to register an account and do the CI bits to upload the reports. https://codecov.io/

**Comment by jeromekelleher** [comment]
LMK if you want a hand setting this up, I've done it a good few times.

**Comment by grahamgower** [comment]
Yeah, that would be great! Do you happen to know what's involved if/when we move the repository?

**Comment by grahamgower** [comment]
Oooh, and this reusable action should make it easy to do the coverage report upload. https://github.com/codecov/codecov-action Care to have a go at it @jeromekelleher?

**Comment by jeromekelleher** [comment]
> Yeah, that would be great! Do you happen to know what's involved if/when we move the repository?

It's easier to do the move first, codecov does get confused quite easily.

**Comment by jeromekelleher** [comment]
Do we have a timeframe in mind for when we might like to move this repo to its long-term home?

**Comment by grahamgower** [comment]
I'd rather not move anything *before* announcing to the consortium. Maybe we can discuss on the call today?

**Comment by jeromekelleher** [comment]
Agreed, definitely we shouldn't move anything before then. Let's talk about it later.
