### ISSUE TITLE
Conversion to/from ms format?

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/demes-python#74]
I'm guessing that a lot of people will want to be able to either convert their existing models to demes or to run demes models through simulators that support ms's demographic model description.

Should we provide ``from_ms()`` and ``to_ms()`` methods? (Or similarly named?)

The ``from_ms`` code wouldn't be too bad, as we could adapt the command line parsing code in [msprime](https://github.com/tskit-dev/msprime/blob/main/msprime/cli.py#L469). With a few small adjustments (i.e., raising ValueErrors rather than calling sys.exit) I think we could reuse the argparse code directly, which doesn't *have* to actually be used in the context of a CLI.

I've been thinking about doing this for the msprime 1.0 Demography API, but it seems to me it would be much more useful here.

Thoughts?

**Comment by grahamgower** [comment]
Yes, that would be an excellent addition.

**Comment by jeromekelleher** [comment]
Good stuff. I'm updating the msprime CLI code at the moment to modernise, so let's not take this on for a bit.
