### ISSUE TITLE
import various msprime.DemographyDebugger functionality

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/demes-python#86]
There's lots of super cool stuff in `msprime.DemographyDebugger`. In particular the `possible_lineage_locations()` and `coalescence_rate_trajectory()` methods (and associated methods) are a very natural fit for inclusion in `demes`. Msprime is GPL, so we'd need to explicitly relicense some parts more permissively.

```
$ git blame demography.py -L800,1600 -c | cut -f2 | sed 's/(//' | sort -u
Graham Gower
Jerome Kelleher
     peter
```
I'm fairly sure Aaron's also an author of this stuff, so I'm not sure why his name doesn't appear (maybe there are other names missed by `git blame` too).

**Comment by jeromekelleher** [comment]
Are you talking about copying the code in @grahamgower or importing msprime to get the functionality? If it's the former, I wouldn't get *too* hung up on the licensing issues...

**Comment by grahamgower** [comment]
Copying the code. Yeah, I don't expect any problems (authors/copyright holders can relicense as they wish), but I didn't want to give the impression that this was being ignored. It can be a real issue in other projects.

**Comment by grahamgower** [comment]
Having numerical algorithms in `demes` is probably not ideal. Users can import a demes model into msprime, so I'm going to close this.
